"""
Django settings for testsql project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ustfiwd5k2gt7r9_p8=^q8iufux@@m45)n$mzm&_364lw=)2r-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []#'localhost','192.168.1.68']  #‘localhost’,


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'accounts.apps.AccountsConfig',
	'upload.apps.UploadConfig',
	'cal.apps.CalConfig',
	#'widget_tweaks',
	#'request_middleware.apps.RequestMiddlewareConfig',
]

MIDDLEWARE = [
    
	'django.middleware.security.SecurityMiddleware',
	#'request_middleware.middleware.RequestMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
	#'login_required.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django_currentuser.middleware.ThreadLocalUserMiddleware',
]

ROOT_URLCONF = 'testsql.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testsql.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
                  # DATABASES = {
                      # 'default': {
                          # 'ENGINE': 'sql_server.pyodbc',
                          # 'NAME':'dms_core',#'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
                  		# 'HOST': 'DESKTOP-2R91M6O',
                          # 'USER': 'fincraftuser',
                          # 'PASSWORD': 'aaa_111',
                  		# #'PORT': 1433,
                  		# #'DRIVER': 'ODBC Driver 17 for SQL Server'
                  		# #'PORT': '1433',    
                  		# }
                  	# }
#HOST = '127.0.0.1'
#PORT = '1433'
#DB_OPTIONS = {
  #  'unicode_results': True,
   # 'host_is_server': True,
    #'extra_params': 'tds_version=7.3;',


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/static/',
]
MEDIA_ROOT= os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# LOGIN_REQUIRED_IGNORE_PATHS = [
    # r'/accounts/logout/$'
    # r'/accounts/signup/$',
    # r'/admin/$',
    # r'/admin/login/$',
    # r'/about/$'
# ]  
# LOGIN_REQUIRED_IGNORE_VIEW_NAMES = [
    # 'home',
    # 'login',
    # 'admin:index',
    # 'admin:login',
    # 'namespace:url_name',
# ]









